### ISSUE TITLE
Build broken on OS X cinder 0.8.6?

### ISSUE THREAD

**Issue by pbeck** [jhurlbut/Cinder-glTF#1]
Great project – I've been looking for a glTF reader!

I'm having trouble getting the sources to build with cinder 0.8.6. Most of the issues are missing cinder header files like GeomIo.h, MayaCamUi.h, but also namespace issues and naming (ci::vec3 for example). Does this build with a specifc earlier version of cinder?

**Comment by jhurlbut** [comment]
This block is meant for the cinder glNext branch which is now known as 0.9.0 and should be the main branch.

**Comment by pbeck** [comment]
Ok. Thanks for the info, I'll try it out.
