### ISSUE TITLE
Upgrading to latest Cinder API

### ISSUE THREAD

**Issue by gooooer** [jhurlbut/Cinder-glTF#2]
Hi James!

I'm using Cinder-glTF in my project and recently I've upgraded to latest Cinder v0.9.1. There were couple of compilation errors in Cinder-glTF that I've already fixed and put in a separate branch.

If you could give me access to this repository then I can create PR on you. Or you can fix errors on your own or I can send you a patch :)

Looking forward for your feedback.

Thanks,
Andrey.

**Comment by jhurlbut** [comment]
Hi Andrey, thanks for fixing errors on the repo. Could you fork it and then do a pull request? I think that's the typical way to do it. Thanks and let me know if you have any problems!

**Comment by gooooer** [comment]
Hi James! Sorry I didn't mention that I could fork. PR is open, cannot assign you to review though. Could you please review it? Thanks!

**Comment by jhurlbut** [comment]
It's updated now. thanks
